name: Publish Image

on:
  push:

env:
 REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Specifying the Java version and architecture
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Build with Gradle
        run: ./gradlew -b ci.gradle package
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Build and push Docker image
        run: |
          docker build --build-arg VERSION="${{ steps.extract_branch.outputs.branch }}" . --file Dockerfile --tag ${{ env.REGISTRY }}/goldenimage/spring-boot-kubernetes-mysql:${{ steps.extract_branch.outputs.branch }}
          docker push ${{ env.REGISTRY }}/goldenimage/spring-boot-kubernetes-mysql:${{ steps.extract_branch.outputs.branch }}